### ISSUE TITLE
提示區塊難以辨識

### ISSUE THREAD

**Issue by dca** [HanGee/joinNow#21]
提示區塊的配色有點難以辨識，要反白才看得到字
![2014-12-18 10 26 36](https://cloud.githubusercontent.com/assets/226619/5482656/6743a4b2-86a0-11e4-9773-b38211d19075.png)

**Comment by yuyaun** [comment]
#24  已經修正摟

**Comment by chiehwen** [comment]
![screenshot_170](https://cloud.githubusercontent.com/assets/232706/5484258/35199daa-86c0-11e4-8897-fe0f6365aa1f.png)

Production 環境下已修正！
